version: "3.9"
services:
  flask:
    build: 
      context: .
      target: runner
    ports:
      - 5000:5000
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
  
  debug:
    profiles: ["debug"]
    build: 
      context: .
      target: debugger
    ports:
      - 5000:5000
      - 5678:5678
    volumes:
      - .:/code

  test:
    profiles: ["test"]
    build: 
      context: .
      target: tester
    ports:
      - 5678:5678
    volumes:
      - .:/code

  watch-test:
    profiles: ["test"]
    build: 
      context: .
      target: tester
    command: sh -c 'find . -type f -name "*.py" | entr -n pytest --tb=short'
    volumes:
      - .:/code
